spring:
  application:
    name: song-storage-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://song-storage-service-db:3306/song_storage_database
    username: root
    password: pass123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  file.name: logs/song-storage-service.log
okta:
  oauth2:
    issuer: "https://dev-46703780.okta.com/oauth2/default"
    client-id: 0oabns9yfhsSiyasb5d7
    client-secret: _QCqZaGecPwzpqmPv0n-1sgjpZ-fovUM1xtqkLWhW97CWf8pCwJAlDSPPE21eA8d
